### ISSUE TITLE
no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by kkaupp** [St3v3nsS/MMSF#4]
<img width="898" alt="error" src="https://github.com/St3v3nsS/MMSF/assets/38055640/d3b0b225-763c-4cbe-b6f7-8aaad052babb">

Hey, will this also work on arm64 devices? Using a M1 Mac. :)

**Comment by St3v3nsS** [comment]
Hi there. Looks like I need to modify the dockerfile to include the platform. I'll do it asap. Thanks for letting me know

**Comment by St3v3nsS** [comment]
I have tried to find a solution, but I am not sure I found something. I changed the docker file, but it might not work. I might need to implement Drozer commands via adb sooner or later. [bac1943](https://github.com/St3v3nsS/MMSF/commit/bac19437cefb590da157a3dadc3064427c6fffce)

**Comment by kkaupp** [comment]
Hey, it's working for me now! Thank you so much for the fast response and your amazing framework!

**Comment by St3v3nsS** [comment]
I'm glad it worked and thank you for your support!
